id: P009332
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:33:52.846257
source_metadata:
  id: bdr:W3CN7859
  title: དབྱིན་བོད་ཤན་སྦྱར་གྱི་ཚིག་མཛོད།
  author: ''
  volumes:
    610e1823ac70435489c72d72d4d0de50:
      image_group_id: I3CN7861
      title: ''
      volume_number: 1
      total_pages: 528
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
